config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :events
  resources :attendances
  #get 'event/index'
  root 'events#index'
  get 'user/show', action: :show, controller: 'users'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user, foreign_key: :user_id, class_name: 'User', dependent: :destroy
  belongs_to :event, foreign_key: :event_id, class_name: 'Event', dependent: :destroy
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user, foreign_key: :user_id, class_name: 'User'
  has_and_belongs_to_many :attendance, join_table: 'attendances', class_name: 'Attendance'

  scope :upcoming_events, -> { where('date > ?', Date.today) }
  scope :previous_events, -> { where('date < ?', Date.today) }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :events, foreign_key: :user_id
  has_and_belongs_to_many :attendances, join_table: 'events', class_name: 'Event'
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  def index
    @attendances = Attendance.all
  end

  def create
    @attendance = Attendance.new(attendance_params)

    respond_to do |format|
      if @attendance.save
        format.html { redirect_to root_path, notice: 'Attendance was successfully created.' }
        format.json { render :index, status: :created, location: @attendance }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @attendance.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def attendance_params
    params.permit(:event_id, :user_id)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :previous_events, only: [:show]
  before_action :upcoming_events, only: [:show]
  before_action :set_event, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[index show]
  before_action :current_user, only: %i[edit update destroy]
  # GET /events or /events.json
  def index
    @events = Event.all
    @past_events = previous_events
    @upcoming_events = upcoming_events
  end

  # GET /events/1 or /events/1.json
  def show
    @event_id = params[:id]
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit; end

  # POST /events or /events.json
  def create
    @event = current_user.events.build(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = Event.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def event_params
    params.require(:event).permit(:title, :description, :date, :user_id)
  end

  def previous_events
    Event.where('date < ?', Time.now)
  end

  def upcoming_events
    Event.where('date >= ?', Time.now)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def show
    @all_events = Event.all
    @events = Event.where(user_id: current_user.id)
    @past_events = @events.previous_events
    @upcoming_events = @events.upcoming_events
  end

  def create
    @user = User.new(params[:user])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/event_helper.rb
module EventHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/event/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">

  <div class="container-fluid">
    <%= link_to 'Private Event App', root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
            
        <% if user_signed_in? %>  
        <%= link_to 'Edit Profile', edit_user_registration_path, class:"nav-link" %>
        <%= link_to 'Create Event', new_event_path, class:"nav-link" %>
        <%= link_to 'View Events', events_path, class:"nav-link" %>
        <%= link_to  'Past/Upcoming Events' , user_show_path, class:"nav-link" %>
        <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class:"nav-link" %>
        <% else %>
            <%= link_to 'Sign In', new_user_session_path, class:"nav-link" %>
            <%= link_to 'Sign Up', new_user_registration_path, class:"nav-link" %>
        <% end %>     

            

            

            
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/events/_form.html.erb
<%= form_with(model: event) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class: "form-control" %>
  </div>
  <br>
  <div class="field form-group">
    <%= form.label :date %>
    <%= form.date_select :date%>
  </div>
  <br>
   <div class="field form-group">
    <%= form.number_field :user_id, id: :event_user_id, value: current_user.id, type: :hidden %>
  </div>
  <br>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<div class="alert alert-info"> Go to <strong>show</strong> for any event to <strong>register your attendance </strong> :) </div>

<%= link_to  'Go to see past and upcoming events' , user_show_path %>

<h2 class="text-center text-muted"> Upcoming Events </h2>

<table class="table table-hover table-bordered">
  <thead class="table-dark">
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Date</th>
      <th>Attendance expected</th>
      <th colspan="3"></th>
    </tr>
  </thead>

 <tbody>
    
    <%  @upcoming_events.each do |event| %>

    <% if event.date >= Time.now %>

      <% if current_user %>
      <tr>
        <td><%= event.title %></td>
        <td><%= event.description %></td>
        <td><%= event.date %></td>
        <td><%= Attendance.where(event_id: event.id).count %></td>
        <td><%= link_to 'Show', event %></td>
        <% if event.user_id == current_user.id %>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event_path(event), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% else %>
        <td></td>
        <td></td>
        <% end %>
      </tr>
      <% end %>
    
    <% end %>
  </tbody>

<% end %>
</table>

<h2 class="text-center text-muted"> Past Events </h2>

<table class="table table-hover table-bordered">
  <thead class="table-dark">
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Date</th>
      <th>Attendance expected</th>
      <th colspan="3"></th>
    </tr>
  </thead>

 <tbody>
    
    <% @past_events.each do |event| %>

    <% if event.date < Time.now %>

      <% if current_user %>
      <tr>
        <td><%= event.title %></td>
        <td><%= event.description %></td>
        <td><%= event.date %></td>        
        <td> Not available </td>
        <td><%= link_to 'Show', event %></td>
        <% if event.user_id == current_user.id %>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event_path(event), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% else %>
        <td></td>
        <td></td>
        <% end %>
      </tr>
      <% end %>
    
    <% end %>
  </tbody>

<% end %>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<div class="jumbotron">
  <h1 class="display-4"><%= @event.title %></h1>
  <p class="lead"><strong>Description:</strong> <%= @event.description %></p>
  <hr class="my-4">
  <p><strong>Date:</strong> <%= @event.date %>.</p>
  <p class="lead">
    <%= link_to 'Back', events_path %>
  </p>
</div>


<p id="notice"><%= notice %></p>
<% if Time.now < @event.date %>
  <% if Attendance.where(event_id: @event.id, user_id: current_user.id) != [] %>
  You are already registered for this event
  <% else %>
  <%= link_to 'Register Attendance with your current account', attendances_path(event_id: params[:id], user_id: current_user.id), method: :post %> 
  <% end %>
<% else %>
  Event finished...
<% end %>


<h2 class="my-5 text-muted text-center">List of attendance</h2>

<% Attendance.all.where(event_id: @event_id).each do | attendance | %>
  
  <ul class="btn btn-secondary">
    <li><%= attendance.user.email %></li>
  </ul>
  <br>
<% end %>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

    <title>Private Events App</title>

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
   <%= render 'event/header'%>
  <div class = "container">
  <br>
    <% if notice %>
      <p class="alert alert-info notice"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>
  </div>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/views/users/show.html.erb
<h1 class="text-center py-5">Your past and upcoming events created </h1>

<%= link_to  'Back', root_path %>

<h2 class="text-center text-muted"> Your Upcoming Events </h2>

<table class="table table-hover table-bordered">
  <thead class="table-dark">
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Date</th>
      <th>Attendance expected</th>
      <th colspan="3"></th>
    </tr>
  </thead>

 <tbody>
    
    <%  @upcoming_events.each do |event| %>


      <% if current_user %>
      <tr>
        <td><%= event.title %></td>
        <td><%= event.description %></td>
        <td><%= event.date %></td>
        <% if Time.now > event.date %>
          <td> Not available </td>
        <% else %>
          <td><%= Attendance.where(event_id: event.id).count %></td>
        <% end %>
        <td><%= link_to 'Show', event %></td>
        <% if event.user_id == current_user.id %>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event_path(event), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% else %>
        <td></td>
        <td></td>
        <% end %>
      </tr>
      <% end %>
    
   
  </tbody>

<% end %>
</table>

<h2 class="text-center text-muted"> Your Past Events </h2>

<table class="table table-hover table-bordered">
  <thead class="table-dark">
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Date</th>
      <th>Attendance expected</th>
      <th colspan="3"></th>
    </tr>
  </thead>

 <tbody>
    
    <% @past_events.each do |event| %>

    

      <% if current_user %>
      <tr>
        <td><%= event.title %></td>
        <td><%= event.description %></td>
        <td><%= event.date %></td>
        <% if Time.now > event.date %>
          <td> Not available </td>
        <% else %>
          <td><%= Attendance.where(event_id: event.id).count %></td>
        <% end %>
        <td><%= link_to 'Show', event %></td>
        <% if event.user_id == current_user.id %>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event_path(event), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% else %>
        <td></td>
        <td></td>
        <% end %>
      </tr>
      
    
    <% end %>
  </tbody>

<% end %>
</table>


<h2 class="text-center text-muted"> Created Events </h2>

<table class="table table-hover table-bordered">
  <thead class="table-dark">
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

 <tbody>
  <% @all_events.each do |event| %>
      <tr>
       <td><%= event.title %></td>
        <td><%= event.description %></td>
        <td><%= event.date %></td>
        <td><%= link_to 'Show', event %></td>
      </tr>
  <% end %>

  </tbody>
</table>